/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restourant;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
import java.sql.DriverManager;

import java.util.HashMap;
import java.util.Map;

import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;

/**
 *
 * @author Windows10
 */
public class demo extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet rs;
    private String sql;
    
    String lvl;
    String id;
    
    private DefaultTableModel tabelModel;
    /**
     * Creates new form entriMeja
     */
    public demo(String lv, String idi) {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        lvl = lv;
        id = idi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        exit.setText("Run Report");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(exit)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(exit)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(516, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Object[][] getDataModel(){
        Object data[][] = null;
        try{
            stat = con.createStatement();
            String sql = "CALL pesananLaporanJoin()"; 
//            String sql = "C"
            rs = stat.executeQuery(sql);
            rs.last();
            int jmlRec = rs.getRow();
            data = new Object[jmlRec][8];
            rs.beforeFirst();
            int i = -1;
            while (rs.next()){
                i++;
                data[i][0] = rs.getString("id_pelanggan");
                data[i][1] = rs.getString("nama");
                data[i][2] = rs.getString("harga");
                data[i][3] = rs.getString("jumlah");
                data[i][4] = rs.getString("total");
                data[i][5] = rs.getString("bayar");
            }
        }catch (SQLException e){
            System.err.println(e.getMessage());
        }
        return data;
    }
   
    public void tampilTabel(){
//        String[] judul = new String[]{"ID", "Menu", "Harga", "Jumlah", "Total", "Bayar"};
//        tabelModel = new DefaultTableModel(getDataModel(), judul);
//        meja.setModel(tabelModel);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tampilTabel();
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        

        try{
            String path= "C:/Users/Windows10/Documents/NetBeansProjects/restourant/src/restourant/laporan.jasper"; 
            Map parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path,parameter, this.con);
            JasperViewer.viewReport(print, false);
        }   
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
         }
    }//GEN-LAST:event_exitActionPerformed
    
    public void reset(){
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(entriMeja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(entriMeja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(entriMeja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(entriMeja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new entriMeja().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    // End of variables declaration//GEN-END:variables
}
