/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restourant;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Windows10
 */
public class menu extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet rs;
    private String sql;
    String lvl;
    String id;
    /**
     * Creates new form menu
     */
    public menu(String lv, String idi) {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        id = idi;
        lvl = lv;
        String upper = lvl.toUpperCase();
//        namal.setText(upper);
//        namal1.setText(upper);
        switch (lv) {
            case "administrator":
                level.setText("Administrator");
                meja.setEnabled(true);
                entriPelanggan.setEnabled(true);
                barang.setEnabled(true);
                pesanan.setEnabled(false);
                laporan.setEnabled(false);
                transaksi.setEnabled(false);
                break;
            case "waiter":
                entriPelanggan.setEnabled(false);
                level.setText("Waiter");
                meja.setEnabled(false);
                barang.setEnabled(true);
                pesanan.setEnabled(true);
                laporan.setEnabled(true);
                transaksi.setEnabled(false);
                break;
            case "kasir":
                entriPelanggan.setEnabled(false);
                level.setText("Kasir");
                meja.setEnabled(false);
                barang.setEnabled(false);
                pesanan.setEnabled(false);
                laporan.setEnabled(true);
                transaksi.setEnabled(true);
                break;
            case "owner":
                entriPelanggan.setEnabled(false);
                level.setText("Owner");
                meja.setEnabled(false);
                barang.setEnabled(false);
                pesanan.setEnabled(false);
                laporan.setEnabled(true);
                transaksi.setEnabled(false);
                break;
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        level = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        entriPelanggan = new javax.swing.JMenuItem();
        meja = new javax.swing.JMenuItem();
        barang = new javax.swing.JMenuItem();
        pesanan = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restourant/homepage-feature-one.jpg"))); // NOI18N

        level.setText("File");
        jMenuBar1.add(level);

        jMenu2.setText("Data Master");

        entriPelanggan.setText("Entri Pelanggan");
        entriPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entriPelangganMouseClicked(evt);
            }
        });
        entriPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(entriPelanggan);

        meja.setText("Meja");
        meja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mejaMouseClicked(evt);
            }
        });
        meja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejaActionPerformed(evt);
            }
        });
        jMenu2.add(meja);

        barang.setText("Barang");
        barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangMouseClicked(evt);
            }
        });
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        jMenu2.add(barang);

        pesanan.setText("Pesanan");
        pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesananMouseClicked(evt);
            }
        });
        pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananActionPerformed(evt);
            }
        });
        jMenu2.add(pesanan);

        transaksi.setText("Transaksi");
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jMenu2.add(transaksi);

        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jMenu2.add(laporan);

        jMenuBar1.add(jMenu2);

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 479, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
        entriBarang em = new entriBarang(lvl, id);
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_barangActionPerformed

    private void pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananActionPerformed
        // TODO add your handling code here:
        pesanan em = new pesanan(lvl, id);
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pesananActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        transaksi em = new transaksi(lvl, id);
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transaksiActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        try{
            String path= "C:/Users/User/Documents/NetBeansProjects/restourant/src/restourant/laporan.jasper"; 
            Map parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path,parameter, this.con);
            JasperViewer.viewReport(print, false);
        }   
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
         }

    }//GEN-LAST:event_laporanActionPerformed

    private void mejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mejaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mejaMouseClicked

    private void barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_barangMouseClicked

    private void pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesananMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pesananMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksiMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_laporanMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        login em = new login();
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void mejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejaActionPerformed
        // TODO add your handling code here:
        entriMeja em = new entriMeja(lvl, id);
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mejaActionPerformed

    private void entriPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entriPelangganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_entriPelangganMouseClicked

    private void entriPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriPelangganActionPerformed
        // TODO add your handling code here:
        entriPelanggan em = new entriPelanggan(lvl, id);
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_entriPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barang;
    private javax.swing.JMenuItem entriPelanggan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem laporan;
    private javax.swing.JMenu level;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem meja;
    private javax.swing.JMenuItem pesanan;
    private javax.swing.JMenuItem transaksi;
    // End of variables declaration//GEN-END:variables
}
